services:
  fastapi:
    build:
      context: ../
      dockerfile: docker/dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../:/src
    command: sh -c "cd app && uvicorn main:app --reload --host 0.0.0.0 --port 3000"